FROM golang:1.19

RUN apt-get update && \
    apt-get install -y libmagickwand-dev
COPY assets /usr/local/share/appbackend
COPY static /usr/local/share/appbackend_static

ADD bin/libcamera-streamer /usr/bin/libcamera-streamer
ADD bin/picamera-streamer /usr/bin/picamera-streamer
ADD bin/usbcam-streamer /usr/bin/usbcam-streamer
ADD bin/raspistill /usr/bin/raspistill

RUN go install github.com/cosmtrek/air@latest
RUN git config --global url.'ssh://git@github.com/'.insteadOf https://github.com/

RUN mkdir ~/.ssh
RUN echo "Host *\n   StrictHostKeyChecking no\n   UserKnownHostsFile=/dev/null" >> ~/.ssh/config

RUN mkdir /app
WORKDIR /app

EXPOSE 8081
ENTRYPOINT ["/bin/sh", "-c", "chmod 600 /root/.ssh/id_rsa && /go/bin/air"]
